Algoritmo EJERCICIO_6_PARA 
	DEFINIR CANT, MENOR_, CONTADOR,NUM COMO REAL;
	ESCRIBIR "INGRESE LA CANTIDAD DE NUMEROS";
	LEER CANT;
	PARA CONTADOR=1 HASTA  CANT CON PASO 1 HACER 
		ESCRIBIR "INGRESE UN NUMERO";
		LEER NUM;
		SI CONTADOR = 1 ENTONCES 
			MENOR_= NUM;
		SiNo
			SI NUM< MENOR_ ENTONCES
				MENOR_=NUM;
			FinSi
		FinSi
		
	FinPara
		Escribir "EL NUMERO MENOR DEL CONJUNTO ES  ", MENOR_;
	
FinAlgoritmo
