Algoritmo EJERCICIO_2_REPETIR
	//LEER 10 NUMEROS E IMPRIMIR SOLAMENTE LOS NUMEROS POSITIVOS
	DEFINIR NUM, CANT Como Entero;
	CANT=0;	
	Escribir "INGRESA UN NUMERO"; 
	Repetir
		LEER NUM;
		CANT=CANT+1;
		SI NUM>0 Entonces
			ESCRIBIR  NUM," POSITIVO";
		FinSi
	Hasta Que (CANT+1=10)
FinAlgoritmo