Algoritmo EJERCICIO_2_MIENTRAS 
	//LEER 10 NUMEROS E IMPRIMIR SOLAMENTE LOS NUMEROS POSITIVOS
	DEFINIR NUM, CANT Como Entero;
	CANT=0;	 
	MIENTRAS CANT<=10 Hacer
		Escribir "INGRESA UN NUMERO"; 
		LEER NUM;
		CANT=CANT+1;
		SI NUM>0 Entonces
			ESCRIBIR  NUM," POSITIVO";
		FinSi
	FIN MIENTRAS
FinAlgoritmo
