Algoritmo EJERCICIO_1_MIENTRAS 
	DEFINIR UND,NUM COMO ENTERO;
	UND=0;
	Escribir "PROGRAMA PARA CONOCER LOS MULTIPLOS DE 3 DESDE 1 HASTA UN NUMERO INGRESADO";
	Escribir "INGRESA UN NUMERO";
	LEER NUM;
	ESCRIBIR "LOS MULTIPLOS DE 3 SON";
	Mientras NUM>=UND+1 Hacer
		UND=UND+1;
		SI UND MOD 3=0 Entonces
			ESCRIBIR, UND;
		FinSi
	Fin Mientras
	
	
FinAlgoritmo
