Algoritmo MULTIPLOS_DE_3_EJERCICIO_1_REPETIR_
	DEFINIR NUM,UND COMO ENTERO;
	UND=1;
	Escribir "PROGRAMA PARA CONOCER LOS MULTIPLOS DE 3 DESDE 1 HASTA UN NUMERO INGRESADO";
	Escribir "INGRESA UN NUMERO";
	LEER NUM;
	escribir "LOS MULTIPLOS DE 3 SON";
	Repetir 
		UND=UND+1;
		SI UND MOD 3=0 ENTONCES;
			Escribir, UND;
		FinSi
	Hasta Que (NUM=UND+1);
	
FinAlgoritmo
