Algoritmo EJERCICIO_1_PARA
	DEFINIR NUM,UND COMO ENTERO;
	UND=0;
	Escribir "PROGRAMA PARA CONOCER LOS MULTIPLOS DE 3 DESDE 1 HASTA UN NUMERO INGRESADO";
	Escribir "INGRESA UN NUMERO";
	LEER NUM;
	escribir "LOS MULTIPLOS DE 3 SON";
	Para UND=1 Hasta NUM Con Paso 1 Hacer
		SI UND MOD 3 =0 ENTONCES
			ESCRIBIR UND;
		FinSi
	Fin Para
FinAlgoritmo
